@URL=http://localhost:8080

GET {{URL}}/app/

###

POST {{URL}}/admin/reset

###

POST {{URL}}/api/validate_chirp
Content-Type: application/json

{
  "body": "I hear Mastodon is better than Chirpy. sharbert I need to migrate"
}


