@URL=http://localhost:8080

GET {{URL}}/api/ggg

###

POST {{URL}}/admin/reset


###

POST {{URL}}/api/users
Content-Type: application/json

{
  "email": "janot@example.com"
}

###

POST {{URL}}/api/chirps
Content-Type: application/json

{
  "body": "teste",
  "userId": "7464b378-7df9-4bbc-bcf0-a762d37cdacc"
}

###
GET {{URL}}/api/chirps
Content-Type: application/json
###
GET {{URL}}/api/chirps/c31aa9db-1363-49c9-9f4a-067e02822131
Content-Type: application/json


