@URL=http://localhost:8080

###

POST {{URL}}/admin/reset

###

POST {{URL}}/api/users
Content-Type: application/json

{
  "email": "mike@bettercall.com",
  "password": "98765"
}

###

POST {{URL}}/api/login
Content-Type: application/json

{
  "email": "mike@bettercall.com",
  "password": "98765"
}

###
POST {{URL}}/api/chirps
Content-Type: application/json

{
  "body": "teste",
  "userId": "68d0f7ed-933f-4628-8233-733bf8c48882"
}

###
GET {{URL}}/api/chirps
Content-Type: application/json
###
GET {{URL}}/api/chirps/3cd5c7c6-01bd-49fc-905a-437db9b8d8fb
Content-Type: application/json


